import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className="text-2xl mt-1">React Auth</h2>
        <h3>Mini Project I learnt from developedbyed Youtube Channel.</h3>
      </main>
    </div>
  );
};

export default Home;
